swagger: "2.0"
info:
  description: "This swagger is to design API that cretaed and fetches artciles on specific date "
  version: "1.0.0"
  title: "Swagger Articles"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "deepakubhalerao@gmail.com"
  
host: "b2vlyx0o64.execute-api.ap-southeast-2.amazonaws.com"
basePath: "/beta/"
tags:
- name: "Articles"
  description: "Articles API"
schemes:
- "https"
paths:
  /article:
    post:
      tags:
      - "addArticle"
      summary: "Create Article"
      description: "Create Article"
      operationId: "addArticle"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "article object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/article"
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: "#/definitions/genArticle"
            
        400:
          description: "Invalid status value"
        
        404:
          description: "Unable to create. A Product with name Article {id} already exist."
        
        401:
          description: "Authentication required"
          
        403:
          description: "Forbidden"
        
        
          
  /article/{articleId}:
    get:
      tags:
      - "getarticleById"
      summary: "Find article by ID"
      description: "Returns a single article"
      operationId: "getarticleById"
      produces:
      - "application/json"
      parameters:
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
        
      - name: "articleId"
        in: "path"
        description: "ID of article to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/genArticle"
        400:
          description: "Invalid status value"
        
        404:
          description: "Unable to create. A Product with name Article {id} already exist."
        
        401:
          description: "Authentication required"
          
        403:
          description: "Forbidden"
          
  /tags/{tagName}/{date}:
    get:
      tags:
      - "getarticleByTagName"
      summary: "Find article by tagname and date"
      description: "Returns articles by date and tags"
      operationId: "getarticleByTagName"
      produces:
      - "application/json"
      parameters:
      - name: "x-api-key"
        in: "header"
        required: true
        type: "string"
      - name: "tagName"
        in: "path"
        description: "ID of article to return"
        required: true
        type: "string"
      - name: "date"
        in: "path"
        description: "ID of article to return"
        required: true
        type: "string"
          
        
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/genTags"
        400:
          description: "Invalid status value"
        
        404:
          description: "Unable to create. A Product with name Article {id} already exist."
        
        401:
          description: "Authentication required"
          
        403:
          description: "Forbidden"      
   
securityDefinitions:
  articlestore_auth:
    type: "oauth2"
    authorizationUrl: "http://articlestore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:articles: "modify articles in your account"
      read:articles: "read your articles"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:

  genTags:
    type: "object"
    properties:
      tag:
        type: "string"
        example: "health"
      count:
        type: "integer"
        example: "3"
      articles:
        type: "array"
        items:
          type: "string"
      related_tags:
        type: "array"
        items:
          type: "string"

  genArticle:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: "1"
      date:
        type: "string"
        example: "yyyyMMdd"
      
      title:
        type: "string"
        example: "article 1"
      body:
        type: "string"
        example: "New health awarenes program"
      tags:
        type: "array"
        items:
          type: "string"

  article:
    type: "object"
    properties:
      title:
        type: "string"
        example: "article 1"
      body:
        type: "string"
        example: "New health awarenes program"
      date:
        type: "string"
        example: "yyyyMMdd"
      tags:
        type: "array"
        items:
          type: "string"

 